'''
Dictionary variables containing player ids and player ranks
'''
PLAYER_ID = {
    'Alexander Dahlstedt': 157,
    'Fredrik Persson': 161,
    'Dennis Kapke': 57,
    'Marcel Noack': 58,
    'Reto Sommer': 143,
    'Walter Erlbruch': 54,
    'Zdenek Majkus': 29,
    'Ivan Macho': 28,
    'Ondrej Skaloud': 33,
    'Alexander Geist': 55,
    'Marek Smejkal': 31,
    'Martin Jecny': 27,
    'Andreas Cederholm': 156,
    'Sebastian Ekängen': 158,
    'Christian Gobetz': 10,
    'Karel Molnar': 30,
    'Igor Pantelimonov': 132,
    'Marian Strasko': 32,
    'Sascha Spreier': 60,
    'Sebastian Heine': 56,
    'Dan Trulsson': 162,
    'Daniel Moser': 141,
    'Rupert Westenthaler': 15,
    'Aki Sillman': 46,
    'Raphael Wietlisbach': 144,
    'Fabian Spies': 13,
    'Ulf Kristiansson': 160,
    'Georgy Lazarev': 130,
    'Jan Anderegg': 138,
    'Youri Bottenberg': 105,
    'Filip Johansson': 159,
    'Sebastian Piekorz': 59,
    'Melanie Hammerschmidt': 63,
    'Karin Olsson': 165,
    'Eva Molnarova': 35,
    'Nicole Birkelbach': 61,
    'Vanessa Peuker': 64,
    'Alena Dolezelova': 34,
    'Lara Jehle': 18,
    'Jasmin Ehm': 62,
    'Marielle Svensson': 166,
    'Yvonne Trachsel': 146,
    'Katerina Tietzova': 37,
    'Rebecca Weber': 147,
    'Jasmin Hansson': 163,
    'Maja Wicki': 48,
    'Laura Fogh Henriksen': 38,
    'Yana Lazareva': 135
}

RANK_W = {
    1: 'Melanie Hammerschmidt',
    2: 'Karin Olsson',
    3: 'Lara Jehle',
    4: 'Eva Molnarova',
    8: 'Nicole Birkelbach',
    5: 'Vanessa Peuker',
    9: 'Alena Dolezelova',
    6: 'Jasmin Ehm',
    7: 'Marielle Svensson',
    10: 'Yvonne Trachsel',
    11: 'Katerina Tietzova',
    12: 'Rebecca Weber',
    13: 'Jasmin Hansson',
    14: 'Maja Wicki',
    15: 'Laura Fogh Henriksen',
    16: 'Yana Lazareva'
}

RANK_M = {
    1: 'Reto Sommer',
    2: 'Alexander Dahlstedt',
    3: 'Marcel Noack',
    4: 'Dennis Kapke',
    5: 'Walter Erlbruch',
    6: 'Zdenek Majkus',
    7: 'Christian Gobetz',
    8: 'Ivan Macho',
    9: 'Ondrej Skaloud',
    10: 'Igor Pantelimonov',
    11: 'Andreas Cederholm',
    12: 'Marian Strasko',
    13: 'Sebastian Ekängen',
    14: 'Fredrik Persson',
    15: 'Alexander Geist',
    16: 'Marek Smejkal',
    17: 'Karel Molnar',
    18: 'Martin Jecny',
    19: 'Sascha Spreier',
    20: 'Sebastian Heine',
    21: 'Dan Trulsson',
    22: 'Daniel Moser',
    23: 'Rupert Westenthaler',
    24: 'Aki Sillman',
    25: 'Raphael Wietlisbach',
    26: 'Fabian Spies',
    27: 'Ulf Kristiansson',
    28: 'Georgy Lazarev',
    29: 'Jan Anderegg',
    30: 'Youri Bottenberg',
    31: 'Filip Johansson',
    32: 'Sebastian Piekorz'
}
